name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy types-psycopg2

    - name: Run mypy
      run: mypy .

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy
      run: echo "Deploying..."
