version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: dasha
      POSTGRES_USER: dasha
      POSTGRES_PASSWORD: dasha

  app:
    build: app
    depends_on:
	- "db" 
    environment:
      POSTGRES_DATABASE: dasha
      POSTGRES_USER: dasha
      POSTGRES_PASSWORD: dasha
      POSTGRES_HOSTNAME: db